[versions]
pmmlModel = "1.6.4"
pmmlEvaluatorExtension = "1.5.16"
rmsScoringLib = "1.4.183"
scoringDocumentationLib = "0.26.0"
topDocumentationPlugin = "0.7.0"
kotlinCsvJvm = "1.7.0"
guava = "30.1-jre"
jaxbApi = "2.3.1"
jaxbRuntime = "4.0.1"
reflections = "0.10.2"
allureUtils = "0.10.0"
scoringAssertionsLib = "0.6.0"
aspectjweaver = "1.9.9.1"
